### ISSUE TITLE
Umlaute in Charakternamen

### ISSUE THREAD

**Issue by sigmaroot** [sigmaroot/GuildBankManager#1]
Umlaute in Charakternamen (Bankchar und/oder Gildenmitglieder) führen bei einem Nutzer zu unerwarteten Problemen:

- Fehlende Chars in der Liste
- Zuweisung von Items an falsche Chars

Ungeklärt ist, welche Chars nicht funktionieren.

Version: 4.6

**Comment by CptAzgar** [comment]
Hey,
mein bankchar heißt "Tränklii" wenn ich mit /gbm inventar die Sachen von jeden Char noch vom Account abspeicher. Wird mir auf der HP der Char "Tränklii" nicht angezeigt. Stattessen sind die Daten (Mats und Gold) auf einen anderen Char von diesen Account.

**Comment by sigmaroot** [comment]
Danke für die Infos, schaue es mir zeitnah an 😀
